In [2]:
import numpy as np
import pandas as pd

# Manipulation de Numpy

In [3]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print(matrix)
# Pour créer une matrice avec 2 colonnes
print(matrix.reshape(-1,2))
print(matrix.trace())
print(np.linalg.inv(matrix[:,1:]))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
18
[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]


In [4]:
print(np.random.normal(0, 1, 10))
print(np.random.randint(10,size=10))
print(np.random.randint(10, size = (2,3)))

[-0.3189812   0.59898963 -0.99281286  0.44374636 -1.35775451  0.06549157
 -0.65617846  1.47549939  0.97978135 -2.53229123]
[3 0 7 7 0 8 7 0 9 9]
[[7 7 2]
 [1 9 6]]


# Manipulation de Pandas
Exemple pris sur le livre de Machine Learning with Python

In [5]:
dataframe = pd.read_csv('../Data/titanic.csv') 
dataframe.head(5)

PassengerId  Survived  Pclass  Name     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    Mr    male  22.0      1      0   7.2500   
1            2         1       1   Mrs  female  38.0      1      0  71.2833   
2            3         1       3  Miss  female  26.0      0      0   7.9250   
3            4         1       1   Mrs  female  35.0      1      0  53.1000   
4            5         0       3    Mr    male  35.0      0      0   8.0500   

      Cabin Embarked  Ticketnumber Ticketprefix  Pclage  
0  no_cabin        S             5            A    66.0  
1         C        C             1           PC    38.0  
2  no_cabin        S             2        STONO    78.0  
3         C        S             1    no_prefix    35.0  
4  no_cabin        S             3    no_prefix   105.0

In [13]:
print(dataframe.shape)
print(dataframe.columns)

(891, 14)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'Cabin', 'Embarked', 'Ticketnumber', 'Ticketprefix',
       'Pclage'],
      dtype='object')


In [6]:
dataframe.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  Name     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    Mr    male  22.0      1      0   7.2500   
1              2         1       1   Mrs  female  38.0      1      0  71.2833   
2              3         1       3  Miss  female  26.0      0      0   7.9250   
3              4         1       1   Mrs  female  35.0      1      0  53.1000   
4              5         0       3    Mr    male  35.0      0      0   8.0500   
..           ...       ...     ...   ...     ...   ...    ...    ...      ...   
886          887         0       2   Rev    male  27.0      0      0  13.0000   
887          888         1       1  Miss  female  19.0      0      0  30.0000   
888          889         0       3  Miss  female  10.0      1      2  23.4500   
889          890         1       1    Mr    male  26.0      0      0  30.0000   
890          891         0       3    Mr    male  32.0      0      0   7.75